-- ========================================
-- 1. 운전면허 테이블 (LICENSES)
-- ========================================
CREATE TABLE LICENSES (
    license_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) NOT NULL,
    name VARCHAR2(100) NOT NULL,
    license_number VARCHAR2(50) NOT NULL UNIQUE,
    resident_registration_number VARCHAR2(14) NOT NULL, -- 주민등록번호 (e.g., 990101-1******)
    issue_date DATE NOT NULL, -- 발급일자
    renewal_start_date DATE, -- 갱신기간 시작일
    renewal_end_date DATE NOT NULL, -- 갱신기간 종료일
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_licenses_user_id FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- ========================================
-- 2. 결제수단 테이블 (PAYMENTS)
-- ========================================
CREATE TABLE PAYMENTS (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) NOT NULL,
    card_number VARCHAR2(100) NOT NULL, -- Encrypted
    card_company VARCHAR2(50) NOT NULL,
    card_expiration_date VARCHAR2(5) NOT NULL, -- MM/YY
    cvc VARCHAR2(3) NOT NULL, -- Encrypted
    is_default NUMBER(1,0) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_payments_user_id FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX idx_licenses_user_id ON LICENSES(user_id);
CREATE INDEX idx_payments_user_id ON PAYMENTS(user_id);

select * from LICENSES;
select * from PAYMENTS;

COMMIT;