-- 테이블 생성 (updated_at 컬럼 포함)
CREATE TABLE NOTICES (
                         id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         category VARCHAR2(255) NOT NULL,
                         title VARCHAR2(255) NOT NULL,
                         content CLOB NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         writer VARCHAR2(255) NOT NULL
);

-- 기존 데이터가 있다면 삭제
DELETE FROM notices;

drop table NOTICES;

-- 1번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '안내', '모카 서비스 점검 안내',
           '보다 안정적인 서비스 제공을 위해 시스템 점검을 실시합니다. 점검 시간에는 서비스 이용이 일시적으로 중단될 수 있으니 양해 부탁드립니다. 점검 시간: 2025년 8월 15일 02:00 ~ 04:00',
           TO_DATE('2025.08.13', 'YYYY.MM.DD'), TO_DATE('2025.08.13', 'YYYY.MM.DD'), '곽수영'
       );

-- 2번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '안내', '개인정보처리방침 개정 안내',
           '개인정보처리방침이 일부 개정되어 안내드립니다. 변경된 내용은 앱 내 설정 메뉴 또는 홈페이지에서 확인하실 수 있습니다. 고객님의 소중한 정보 보호를 위해 항상 최선을 다하겠습니다.',
           TO_DATE('2025.06.08', 'YYYY.MM.DD'), TO_DATE('2025.06.08', 'YYYY.MM.DD'), '곽수영'
       );

-- 3번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '신규서비스', '카카오 페이 결제 오픈',
           '이제 모카에서도 카카오페이를 통해 간편하게 결제할 수 있습니다. 더 빠르고 편리해진 결제 시스템을 경험해보세요!',
           TO_DATE('2025.05.05', 'YYYY.MM.DD'), TO_DATE('2025.05.05', 'YYYY.MM.DD'), '곽수영'
       );

-- 4번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '업데이트', '람보르기니 업데이트',
           '드림카의 아이콘, 람보르기니 우라칸 모델이 신규 입고되었습니다. 지금 바로 예약하여 특별한 드라이빙을 즐겨보세요.',
           TO_DATE('2025.04.28', 'YYYY.MM.DD'), TO_DATE('2025.04.28', 'YYYY.MM.DD'), '곽수영'
       );

-- 5번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '업데이트', '예약 시스템 성능 개선',
           '예약 시스템의 응답 속도와 안정성을 개선하여 더욱 쾌적한 예약 경험을 제공합니다. 사용 중 불편한 점이 있으시면 언제든지 고객센터로 문의해주세요.',
           TO_DATE('2025.04.15', 'YYYY.MM.DD'), TO_DATE('2025.04.15', 'YYYY.MM.DD'), '곽수영'
       );

-- 6번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '안내', '서비스 이용약관 개정 안내',
           '서비스 이용약관이 개정되었습니다. 변경된 약관의 효력 발생일은 2025년 4월 20일입니다. 자세한 내용은 공지사항 전문을 확인해주시기 바랍니다.',
           TO_DATE('2025.03.20', 'YYYY.MM.DD'), TO_DATE('2025.03.20', 'YYYY.MM.DD'), '곽수영'
       );

-- 7번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '신규서비스', '신규 차종 2종 추가 안내',
           '고객님들의 다양한 취향을 만족시켜드리기 위해 포드 머스탱, 애스턴 마틴 DB12 모델을 새롭게 추가했습니다. 많은 이용 바랍니다.',
           TO_DATE('2025.02.10', 'YYYY.MM.DD'), TO_DATE('2025.02.10', 'YYYY.MM.DD'), '곽수영'
       );

-- 8번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '업데이트', '모바일 앱 UI/UX 전면 개편',
           '더욱 직관적이고 편리한 사용성을 제공하기 위해 모카 앱의 디자인과 사용자 경험을 전면 개편했습니다. 새로워진 모카를 만나보세요!',
           TO_DATE('2025.01.15', 'YYYY.MM.DD'), TO_DATE('2025.01.15', 'YYYY.MM.DD'), '곽수영'
       );

-- 9번 공지
INSERT INTO notices (category, title, content, created_at, updated_at, writer)
VALUES (
           '안내', '장기 렌트 고객을 위한 특별 혜택 안내',
           '한 달 이상 장기 렌트 하시는 고객님들께 월 대여료 15% 할인 및 무료 세차 쿠폰 2매를 증정합니다. 자세한 내용은 이벤트 페이지를 참고해주세요.',
           TO_DATE('2024.12.20', 'YYYY.MM.DD'), TO_DATE('2024.12.20', 'YYYY.MM.DD'), '곽수영'
       );

-- 데이터 삽입 확인
COMMIT;
SELECT * FROM notices ORDER BY id DESC;
